name: Build Minecraft Plugin

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: 16

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build plugin
      run: ./gradlew build
